# Generated by Django 2.2.7 on 2021-11-21 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nationality', models.CharField(blank=True, max_length=25, null=True)),
                ('name', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'author',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=35, null=True)),
                ('author', models.CharField(blank=True, max_length=25, null=True)),
                ('genre', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='Copy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copy_num', models.IntegerField()),
                ('isbn', models.ForeignKey(db_column='isbn', on_delete=django.db.models.deletion.DO_NOTHING, related_name='copy_isbn', to='main.Book')),
            ],
            options={
                'db_table': 'copy',
                'unique_together': {('isbn', 'copy_num')},
            },
        ),
        migrations.CreateModel(
            name='Librarian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='librarian_user', to='main.Account')),
            ],
            options={
                'db_table': 'librarian',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('publisher_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=25, null=True)),
                ('country', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'publisher',
            },
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reader_user', to='main.Account')),
            ],
            options={
                'db_table': 'reader',
            },
        ),
        migrations.CreateModel(
            name='Write',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='author_write', to='main.Author')),
                ('isbn', models.ForeignKey(db_column='isbn', on_delete=django.db.models.deletion.DO_NOTHING, to='main.Book')),
            ],
            options={
                'db_table': 'write',
                'unique_together': {('author', 'isbn')},
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copy_num', models.IntegerField()),
                ('stock_date', models.DateField(blank=True, null=True)),
                ('isbn', models.ForeignKey(db_column='isbn', on_delete=django.db.models.deletion.DO_NOTHING, related_name='stock_isbn', to='main.Copy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='stock_user', to='main.Librarian')),
            ],
            options={
                'db_table': 'stock',
                'unique_together': {('user', 'copy_num', 'isbn')},
            },
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copy_num', models.IntegerField()),
                ('rent_date', models.DateField(blank=True, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('isbn', models.ForeignKey(db_column='isbn', on_delete=django.db.models.deletion.DO_NOTHING, related_name='rent_isbn', to='main.Copy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rent_user', to='main.Reader')),
            ],
            options={
                'db_table': 'rent',
                'unique_together': {('user', 'copy_num', 'isbn')},
            },
        ),
        migrations.CreateModel(
            name='Print',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.ForeignKey(db_column='isbn', on_delete=django.db.models.deletion.DO_NOTHING, related_name='print_isbn', to='main.Book')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Publisher')),
            ],
            options={
                'db_table': 'print',
                'unique_together': {('publisher', 'isbn')},
            },
        ),
    ]
