# Generated by Django 2.2.7 on 2021-11-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='copy_num',
            field=models.BigIntegerField(),
        ),
    ]
