# Generated by Django 2.2.7 on 2021-11-21 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211121_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reader_user', to='main.Account'),
        ),
    ]
